delete http://localhost:3001/api/persons/5d267b052c14a200179c1012
content-type: application/json

###
get http://localhost:3001/info

###
get http://localhost:3001/api/persons

###
get http://localhost:3001/api/persons/5d253d7a62a80b7e8dd49c5a

###
post http://localhost:3001/api/persons
content-type: application/json

{
    "name" : "Tasha",
    "number": "555-69493-323"
}

###
put http://localhost:3001/api/persons/5d279c26076bf60c785bdaff
content-type: application/json

{
    "name":"Bob",
    "number":"555-777-889"
}