get http://localhost:3003/api/blogs

###

get http://localhost:3003/api/blogs/5d30ad8da91bcb15b4b15a02

###

post http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "New post from me",
    "author": "Vanya",
    "url": ""
}

###

put http://localhost:3003/api/blogs/5d30ad8da91bcb15b4b15a02
Content-Type: application/json

{
    "title": "New posts",
    "author": "Ivan Lytovka",
    "url": "lytovka.com",
    "likes":54
}

###

delete http://localhost:3003/api/blogs/aba

###

get http://localhost:3003/api/users/

###

post http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "userId": "5d35f3456cfd46460481ec26",
    "title": "Test post number 2",
    "author": " Ivan Lytovka",
    "url": "lytovka.com",
    "likes":10
}


###

post http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "tanya",
    "name": "Tanya",
    "password": "Aaaaaaa"
}

###

post http://localhost:3003/api/login/
Content-Type: application/json

{
    "username": "lytovka",
    "password": "Aa11111111"   
}