get http://localhost:3003/api/blogs

###

get http://localhost:3003/api/blogs/5d30ad8da91bcb15b4b15a02

###

post http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "New post from me",
    "author": "Vanya",
    "url": ""
}

###

delete http://localhost:3003/api/blogs/5d30ad8da91bcb15b4b15a04