get http://localhost:3003/api/blogs

###

get http://localhost:3003/api/blogs/5d2d5830e795da1f680ae830

###

post http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "New post from another author",
    "author": "Tanya",
    "url": "tanya.com",
    "likes":35
}